import 'dart:math';
import "dart:io";

void printStars(int n) {
	String star = "*";
	while(n>0) {
		star = star + "*";
		n--;
	}
	print(star);
}

String? prompt(String promptText) {
	print(promptText);
	String? pr = stdin.readLineSync();
	return pr;
}

void main() {
	print("This is a guessing number game");
	printStars(45);
	print("Your task is to guess a number randomly generated by computer");
	print("The number is in the range 1 - 100");
	print("You have 10 chances");
	print("All the best");
	printStars(45);
	int chances = 1;
	var random = new Random();
	int theNum = (random.nextInt(99)) + 1;
	bool win = false;

	while(chances<=10) {
		int guess = int.parse(prompt("Guess number: ")!);
		if(guess == theNum) {
			print("Hurrah! You win the game!");
			print("You took ${chances} chances to win");
			win = true;
			break;
		}
		else {
			if(guess>theNum) {
				print("Try a smaller number");
			}
			else {
				print("Try a larger number");
			}
		}
		chances++;
		printStars(45);
	}
	if (!win) {
		print("Better luck next time!");
	}
	printStars(45);
}